const SimpsonsArticle1 = `When The Simpsons had premiered on Fox, in 1989, prime - time television was somewhat lacking in comedy.Despite a few bright spots such as Cheers and the barbed, happily crude Roseanne, the sitcom roost was ruled by didactic, saccharine family fare: The Cosby Show, Full House, Growing Pains, Family Matters.Of the last— the show that gave the world Urkel— Tom Shales piously declared in The Washington Post. A decent human being would have a hard time not smiling. It was on this wan entertainment landscape that The Simpsons planted its flag.Prime time had not seen an animated sitcom since The Flintstones, in the 1960 s, and the Christmas special with which The Simpsons debuted made clear that Springfield and Bedrock were separated by more than just a few millennia.In Simpsons Roasting on an Open Fire, Homer takes a job as a department - store Santa after the family's emergency money is spent on tattoo removal for Bart. Following a motivational chat from Bart on the nature of Christmas miracles on television—meta-commentary was a Simpsons hallmark from the start—Homer risks his earnings at the track, on a dog named Santa's Little Helper.When the dog comes in dead last, the family adopts him.While the ending sounds a tad cheesy, and it was, the seeds had been planted: up against impossible odds, and one another, the family ultimately bonded together and overcame. And the gags were solid: Homer is despondent at the length of his children 's Christmas pageant; a tattoo artist unquestioningly accepts 10-year-old Bart as an adult; the family's Christmas decorations are clearly pathetic in contrast to the Flanders family 's next door. Critical reaction was nearly unanimous. Couldn't be better… not only exquisitely weird but also as smart and witty as television gets, raved the Los Angeles Time.`

const CookingArticle1 = `A fish like cod, known for its mild flavour and versatility, does well when paired with most flavours, including the bold ones associated with Basque cooking. However, fish can seem intimidating to many of us because for lack of experience cooking it, fear of committing the cardinal sin of overcooking.
Cooking fish at a lower temperature – whether roasting or pan-frying – makes it easier to catch it when it’s cooked to perfection and before it’s gone too far. For Boulud’s recipe, the temperature of the pan is turned down to low once the cod has been added to the pan, for example.
While Andrea fairly accurately recreated Boulud’s memory only from taste, those of us wanting to attempt Cod Basquaise at home have a little help – Daniel Boulud  shared his recipe with us! This recipe has been modified slightly for the home cook.`


const trainingData = [
  {content: SimpsonsArticle1, tags:"The Simpsons, Animated Comedy" },
  {content: CookingArticle1,  tags:"Cooking, Recipe" }
]

module.exports = trainingData;
